import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';


const sidebars: SidebarsConfig = {
  agileSidebar: [{type: 'autogenerated', dirName: 'agile'}],
  jellSidebar: [{type: 'autogenerated', dirName: 'jell'}],
  teamSidebar: [{type: 'autogenerated', dirName: 'team'}],
  developmentSidebar: [{type: 'autogenerated', dirName: 'development'}],
};

export default sidebars;
